Theanoを使った計算を試してみる

In [1]:
#coding: utf-8
import theano
import theano.tensor as T

# シンボルの生成
# xはdoubleのスカラー型
x = T.dscalar('x')
print type(x)

# シンボルを組み立てて数式を定義（これもまたシンボル）
y = x ** 2
print type(y)

# シンボルを使って関数を定義
# ここでコンパイルされる
f = theano.function(inputs=[x], outputs=y)
print type(f)

# 関数を使ってxに具体的な値を入れてyを計算
print f(1)
print f(2)
print f(3)
print f(4)
print f(5)

<class 'theano.tensor.var.TensorVariable'>
<class 'theano.tensor.var.TensorVariable'>
<class 'theano.compile.function_module.Function'>
1.0
4.0
9.0
16.0
25.0


In [2]:
#coding: utf-8
import theano
import theano.tensor as T

# シンボルの生成
# xはdoubleのスカラー型
x = T.vector('x')
print type(x)

# シンボルを組み立てて数式を定義（これもまたシンボル）
y = x ** 2
print type(y)

# シンボルを使って関数を定義
# ここでコンパイルされる
f = theano.function(inputs=[x], outputs=y)
print type(f)

# 関数を使ってxに具体的な値を入れてyを計算
print f([1,2,3])


<class 'theano.tensor.var.TensorVariable'>
<class 'theano.tensor.var.TensorVariable'>
<class 'theano.compile.function_module.Function'>
[ 1.  4.  9.]


In [4]:
#coding: utf-8
import theano
import theano.tensor as T

# シンボルの生成
# xはdoubleのスカラー型
x = T.dmatrix('x')
print type(x)

# シンボルを組み立てて数式を定義（これもまたシンボル）
y = x ** 3
print type(y)

# シンボルを使って関数を定義
# ここでコンパイルされる
f = theano.function(inputs=[x], outputs=y)
print type(f)

# 関数を使ってxに具体的な値を入れてyを計算
print f([[1,2,3], [4,5,6]])


<class 'theano.tensor.var.TensorVariable'>
<class 'theano.tensor.var.TensorVariable'>
<class 'theano.compile.function_module.Function'>
[[   1.    8.   27.]
 [  64.  125.  216.]]


シグモイド関数を使った計算をしてみる

In [5]:
#coding: utf-8
import theano
import theano.tensor as T

# シンボルを定義
x = T.dmatrix('x')

# シンボルを組み合わせて数式を定義
# s = T.nnet.sigmoid(x)でもOK
s = 1 / (1 + T.exp(-x))

# シンボルを使って関数化
sigmoid = theano.function(inputs=[x], outputs=s)

# 実際の値を使って計算
print sigmoid([[0, 1], [-1, -2]])

[[ 0.5         0.73105858]
 [ 0.26894142  0.11920292]]


共有変数について学ぶ

In [6]:
#coding: utf-8
import numpy as np
import theano

# データを共有変数に読み込む
data = np.array([[1,2,3], [4,5,6]], dtype=theano.config.floatX)
X = theano.shared(data, name='X', borrow=True)
print type(X)
print X.get_value()

<class 'theano.tensor.sharedvar.TensorSharedVariable'>
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
