In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from scipy import fftpack
from scipy import signal
import numpy as np
import pandas as pd
import datetime

In [2]:
cd ~/Documents/01_SensorData/2016_04_12/cleaning-addingLABEL/

/home/takeyama/Documents/01_SensorData/2016_04_12/cleaning-addingLABEL


In [4]:
left_hand = pd.read_csv('Cleaning-Conv-left-hand-ags.csv',parse_dates=['Time'])
#left_hand.Time=pd.to_timedelta(left_hand.Time)
left_leg = pd.read_csv('Cleaning-Conv-left-leg-ags.csv',parse_dates=['Time'])
#left_leg.Time=pd.to_timedelta(left_leg.Time)
right_hand = pd.read_csv('Cleaning-Conv-right-hand-ags.csv',parse_dates=['Time'])
#right_hand.Time=pd.to_timedelta(right_hand.Time)
right_leg = pd.read_csv('Cleaning-Conv-right-leg-ags.csv',parse_dates=['Time'])
#right_leg.Time=pd.to_timedelta(right_leg.Time)
west = pd.read_csv('Cleaning-Conv-west-ags.csv',parse_dates=['Time'])
#west.Time=pd.to_timedelta(west.Time)

In [12]:
fftpack.fft(left_hand.AccX) 

array([ 39686.01890000   +0.j        ,  -6195.56747794+4295.81877706j,
         -766.14636653-1692.74510287j, ...,    854.11185374+5153.44608764j,
         -766.14636653+1692.74510287j,  -6195.56747794-4295.81877706j])

In [75]:
def sliding_window(labeling_data,freq, overlap):
    count =0
    start =labeling_data.Time[0]
    goal = start+datetime.timedelta(seconds=freq)
    yield labeling_data[(start <= labeling_data.Time) &(labeling_data.Time< goal)]
    
    while (goal <  left_hand.Time.max()):
        count +=1
        start =start+datetime.timedelta(seconds=freq*overlap)
        goal = start+datetime.timedelta(seconds=freq)
        yield labeling_data[(start <= labeling_data.Time) &(labeling_data.Time< goal)]

In [99]:
#サンプリング数を16として計算していく
df=sliding_window(left_hand,0.16,0.5)

In [100]:
left_hand.Time.max()

Timestamp('2016-04-21 18:15:30.396000')

In [98]:
df.next().Time.max()

Timestamp('2016-04-21 18:06:15.926000')

In [101]:
data =[]
while ( df.next().Time.max() < left_hand.Time.max() ):
    data.append( fftpack.fft( df.next().AccX ) )

In [103]:
len(data)

3466

[array([ 11.35310000+0.j        ,  -0.36461541-0.51484769j,
          0.02378629-0.09792662j,   0.06542821-0.04280195j,
          0.03410000-0.0288j    ,   0.05565286-0.01395823j,
          0.04641371-0.03472662j,   0.07953434-0.01760396j,
          0.05270000+0.j        ,   0.07953434+0.01760396j,
          0.04641371+0.03472662j,   0.05565286+0.01395823j,
          0.03410000+0.0288j    ,   0.06542821+0.04280195j,
          0.02378629+0.09792662j,  -0.36461541+0.51484769j]),
 array([ 6.60910000+0.j        ,  0.39483586-0.711123j  ,
         0.18390574-0.37134417j,  0.18116594-0.2466701j ,
         0.13940000-0.1553j    ,  0.16622490-0.09816583j,
         0.15689426-0.05334417j,  0.15337330-0.01901873j,
         0.14490000+0.j        ,  0.15337330+0.01901873j,
         0.15689426+0.05334417j,  0.16622490+0.09816583j,
         0.13940000+0.1553j    ,  0.18116594+0.2466701j ,
         0.18390574+0.37134417j,  0.39483586+0.711123j  ]),
 array([ 9.27610000+0.j        ,  0.52814185+2.32603