In [1]:
import numpy as np

In [4]:
a = np.array( [i for i in range(10)] )

In [5]:
b = np.array( [i for i in range(10,20)])

In [6]:
c = np.array( [i for i in range(20,30)])

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
c

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
abc = np.array( [i for i in [a,b,c]] )

In [18]:
abc.shape

(3, 10)