In [2]:
import numpy as np

In [3]:
np.empty(3)

array([ 0.,  1.,  2.])

In [4]:
x=y=z=np.arange(0.0,5.0,1.0)

In [5]:
np.savetxt('test.out', x, delimiter=',')

In [6]:
ls

Deal-with-FFT-csv-file.ipynb  numpy-tutorial.ipynb  test.out


In [108]:
a=np.array([0,1,2])

In [20]:
b=np.array(['a','b','c'])

In [28]:
c=np.vstack( (np.hstack((a[0],b)),np.hstack((a[1],b)),np.hstack((a[2],b))) )

In [29]:
c

array([['0', 'a', 'b', 'c'],
       ['1', 'a', 'b', 'c'],
       ['2', 'a', 'b', 'c']], 
      dtype='|S21')

In [51]:
d=np.array(np.random.randn(500,1))

In [52]:
d[0]

array([-0.43677273])

In [57]:
c =np.hstack( (d[0],b) )
for l in d[1:]:
    c =np.vstack( (c,(np.hstack( (l,b) ))) )

In [58]:
c

array([['-0.436772728054', 'a', 'b', 'c'],
       ['1.65934838617', 'a', 'b', 'c'],
       ['-1.30312041511', 'a', 'b', 'c'],
       ..., 
       ['-1.59132927164', 'a', 'b', 'c'],
       ['-0.784099909459', 'a', 'b', 'c'],
       ['0.349048788878', 'a', 'b', 'c']], 
      dtype='|S32')

In [60]:
import pandas as pd
rng = pd.date_range('1/1/2014',periods=100,freq='D')

# 乱数でデータフレームを作っていく、インデックスは ABCD とする
df1 = pd.DataFrame(np.random.randn(100, 4), index = rng, columns = ['A','B','C','D'])
df2 = pd.DataFrame(np.random.randn(100, 4), index = rng, columns = ['A','B','C','D'])
df3 = pd.DataFrame(np.random.randn(100, 4), index = rng, columns = ['A','B','C','D'])

# これらデータフレームをまとめて Panel オブジェクトをつくる
pf = pd.Panel({'df1':df1,'df2':df2,'df3':df3})

pf

df1


A         B         C         D
2014-01-01 -2.030348  1.088840 -1.714988 -1.301796
2014-01-02 -0.300063 -0.152380  0.596220 -1.029267
2014-01-03  0.314136  1.048867 -0.231731 -0.123225
2014-01-04 -0.912218  0.909034  1.683757  0.242269
2014-01-05  0.132262 -0.637635  0.590908 -0.455167
2014-01-06 -0.201947 -0.497691 -0.157533  0.173935
2014-01-07  0.238321 -0.217319 -0.420493 -0.988766
2014-01-08 -1.348907 -1.518383  1.821123  1.429980
2014-01-09 -0.334511  1.036309 -2.253125 -0.827528
2014-01-10 -0.706291  1.327520 -0.956838  0.071963
2014-01-11 -1.177240  1.374746  0.602795 -0.550558
2014-01-12  0.518931 -2.212615  1.113966 -0.300775
2014-01-13  1.070170  0.355140  2.108908 -1.737691
2014-01-14 -0.202757  0.340760  0.757309 -0.174152
2014-01-15  0.863090  0.697545  0.175854  0.107085
2014-01-16  0.651723 -0.008323 -1.023004 -1.109805
2014-01-17  0.171641 -0.406347 -1.093364  1.211658
2014-01-18 -0.229306  0.294924  0.347061  0.822343
2014-01-19  1.207394 -0.987661  0.261802 -0.470124
2014-01-20  1.001610 -1.166117  1.179222  0.378278
2014-01-21 -0.346392 -0.312463 -0.848045 -0.193189
2014-01-22 -2.220054  0.322433 -1.868263  0.145460
2014-01-23  0.279434  0.518552  1.403580  0.033209
2014-01-24 -0.189831 -1.205629 -0.775258  0.070272
2014-01-25 -0.704007 -2.513074 -0.632228  0.538788
2014-01-26  0.836490 -0.328769  1.031534  1.288624
2014-01-27  0.991530  1.809683  0.757067  1.614906
2014-01-28  0.233829 -1.139374  1.443593  1.198165
2014-01-29  0.601489  1.500124 -0.834012 -2.098834
2014-01-30 -0.652051 -0.706375  1.406991  0.392957
...              ...       ...       ...       ...
2014-03-12 -0.448505  1.640198  0.214986 -0.406866
2014-03-13  0.445553 -0.969804  0.639889 -0.361745
2014-03-14 -0.527908 -0.860491 -0.364795  0.713167
2014-03-15 -1.645985 -0.274356 -1.126498  0.226725
2014-03-16 -0.227032 -2.376109 -0.162007  0.366290
2014-03-17 -2.235066 -0.190065 -0.050485  0.797589
2014-03-18 -1.041738 -1.051874 -0.751094  1.062232
2014-03-19 -0.582826  0.124350 -1.216674  0.737198
2014-03-20  0.463540  0.769738  0.690852 -0.373624
2014-03-21  0.633902 -1.950877  0.690288  1.133754
2014-03-22 -1.956697 -0.091758 -1.482437 -0.742334
2014-03-23  0.007927 -0.818243  0.129575 -1.104456
2014-03-24 -1.765754  2.045124  1.270709  0.077275
2014-03-25 -0.055307 -0.629733  1.442377  0.135838
2014-03-26 -0.041331  0.647296 -1.344290  0.088793
2014-03-27 -0.347047  0.055077 -1.297156  0.219560
2014-03-28  1.887264  0.383805 -0.185953 -1.579982
2014-03-29  1.371099  0.564256  0.679876  0.406620
2014-03-30 -0.446337  0.523351  0.684117 -2.703178
2014-03-31 -1.197391  0.268837 -1.302292  0.839139
2014-04-01  2.835714 -0.679544 -2.144163 -0.455876
2014-04-02  1.297904  0.170669  1.076500 -0.706860
2014-04-03 -0.982154  1.213624  1.369915 -0.639954
2014-04-04  0.087032  0.301275 -1.262421 -1.448267
2014-04-05 -0.708794 -0.689934 -1.541344  1.020822
2014-04-06  2.906225 -0.476724  0.548576  1.296231
2014-04-07  0.114133  0.072880 -0.674422 -0.868722
2014-04-08  0.870866 -1.808665  0.038570 -0.037494
2014-04-09 -0.451460 -0.410687 -1.181434 -0.589260
2014-04-10 -0.764129  0.627623  0.480900 -0.102483

[100 rows x 4 columns]

In [109]:
a

array([0, 1, 2])

In [110]:
b

array(['a', 'b', 'c'], 
      dtype='|S1')

In [69]:
for n in range(len(a)):
    c= np.insert(a,n,[a[n],a[n],a[n],a[n],a[n],a[n]])
    

In [100]:
d=[]
for data in b:
    for i in range(6):
        d.append(data)

In [101]:
d

['a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'c',
 'c',
 'c',
 'c',
 'c',
 'c']

In [111]:
np.vstack( (a,b) )

array([['0', '1', '2'],
       ['a', 'b', 'c']], 
      dtype='|S21')

In [112]:
df = pd.DataFrame( [[0,1,2], [3,4,5], [6,7,8], [9,10,11]] ) # 4x3 table
df.columns = ['c0', 'c1', 'c2']
df.index = ['r0', 'r1','r2','r3']
df.shape   #=> (4,3)


(4, 3)

In [113]:
df

c0  c1  c2
r0   0   1   2
r1   3   4   5
r2   6   7   8
r3   9  10  11

In [114]:
df1 = pd.DataFrame( [{'c0':1, 'c1':2}, {'c1':1, 'c2':2}, {'c0':1, 'c2':2}] )

In [115]:
df1

c0   c1   c2
0  1.0  2.0  NaN
1  NaN  1.0  2.0
2  1.0  NaN  2.0

In [125]:
list1=[[ 0.35804487-0.01519195j, -0.09451400-0.10396996j,
         0.05838963-0.10452798j, -0.00347080-0.07505361j,
         0.02233362-0.04416239j,  0.01685079+0.00862261j,
         0.04096550+0.0365221j ,  0.11865038+0.04220009j],
         [-0.35210660-0.63264773j,  0.02284033-0.09660578j,
         0.04796848-0.04358906j,  0.03218321-0.05969557j,
         0.05991556-0.03240392j,  0.08297981-0.03868062j,
         0.07200175+0.00649903j,  0.05651747-0.01512774j]]

In [127]:
array=np.array(list1)

In [129]:
array.size

16

In [131]:
a=np.array([1,2,3])

In [132]:
b=np.array([3,4,5])

In [133]:
c=np.array([5,6,7])

In [135]:
d=np.vstack( (a,b) )

In [136]:
d

array([[1, 2, 3],
       [3, 4, 5]])

In [138]:
d=np.vstack( (d,c) )

In [139]:
d

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [140]:
e=np.array([])

In [141]:
np.vstack( (e,a) )

ValueError: all the input array dimensions except for the concatenation axis must match exactly